### ISSUE TITLE
Missing license file in maven repository

### ISSUE THREAD

**Issue by desombre** [playframework/netty-reactive-streams#169]
Hello,

when looking the source in the maven repo (https://repo1.maven.org/maven2/com/typesafe/netty/netty-reactive-streams/2.0.8/) no license file is present. They are usually located in the `META-INF` folder together with the `MANIFEST.MF` file.
We have some automated checks running in our project pipeline and they keep flagging this dependency.

Kind regards

**Comment by mkurz** [comment]
Thanks for the heads up. Feel free to open a pull request to fix that if it's an urgent matter on your side.
