### ISSUE TITLE
Add an Automatic-Module-Name manifest entry

### ISSUE THREAD

**Issue by varunnvs92** [playframework/netty-reactive-streams#39]
It is recommended for java libraries in public repositories like Maven Central to add Automatic-Module-Name manifest entry. This allows the consumers of the library to move to Java 9 modularization and depend on the Automatic-Module-Name value instead of the name derived from the Jar file. This way, your consumers won't need to make changes when your library is eventually converted to a Java 9 module.

Adding Automatic-Module-Name doesn't affect any code and will simply make a name reservation until an actual module-info.java will be added eventually. More details can be found in this [article](https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers).

As for the module name, I think ```com.typesafe.netty``` seems reasonable. [This article](http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html) has best naming practices for JPMS modules.

[AWS Java SDK v2](https://github.com/aws/aws-sdk-java-v2) has a dependency on your library and we are adding module-info files to our library. But we need this change to be done before we can add move to JPMS. I can create a PR if you think it would be helpful to prioritize this request.

**Comment by schmitch** [comment]
actually I think we could even add a module-info directly.

**Comment by varunnvs92** [comment]
Thanks, that would be great. Do you have a timeline in mind?

**Comment by varunnvs92** [comment]
@schmitch 
Any updates on this? I can send the PR for adding the "Automatic-Module-Name" header. 

If you want to module-info file, then it would make sense for your team to work on it as you would know better on which packages you want to export and which packages you want to hide etc.

**Comment by schmitch** [comment]
well you can just create a PR with the `Automatic-Module-Name` header.

**Comment by varunnvs92** [comment]
When do you plan to release a new version to Maven that has this change?
